/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juego_xo;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class app_XO extends javax.swing.JFrame {
   
   String turno = "X";
   JLabel lbs[]=new JLabel[9];
   int contaX = 0;
   int contaY = 0;
   int vs[][]={
      {1,2,3},{4,5,6},{7,8,9},
      {1,4,7},{2,5,8},{3,6,9},
      {3,5,7},{1,5,9}};
   /**
    * Creates new form app_XO
    */
   public app_XO() {
      initComponents();
      blok();
      this.setLocationRelativeTo(null);
      lbs[0] = lb_1;
      lbs[1] = lb_2;
      lbs[2] = lb_3;
      lbs[3] = lb_4;
      lbs[4] = lb_5;
      lbs[5] = lb_6;
      lbs[6] = lb_7;
      lbs[7] = lb_8;
      lbs[8] = lb_9;
   }
   public void blok(){
      lb_1.setVisible(false);
      lb_2.setVisible(false);
      lb_3.setVisible(false);
      lb_4.setVisible(false);
      lb_5.setVisible(false);
      lb_6.setVisible(false);
      lb_7.setVisible(false);
      lb_8.setVisible(false);
      lb_9.setVisible(false);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      btn_star = new javax.swing.JButton();
      lb_1 = new javax.swing.JLabel();
      lb_2 = new javax.swing.JLabel();
      lb_3 = new javax.swing.JLabel();
      lb_4 = new javax.swing.JLabel();
      lb_5 = new javax.swing.JLabel();
      lb_6 = new javax.swing.JLabel();
      lb_7 = new javax.swing.JLabel();
      lb_8 = new javax.swing.JLabel();
      lb_9 = new javax.swing.JLabel();
      jLabel1 = new javax.swing.JLabel();
      jLabel11 = new javax.swing.JLabel();
      lb_X = new javax.swing.JLabel();
      fondo = new javax.swing.JLabel();
      jButton1 = new javax.swing.JButton();
      lb_0 = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

      btn_star.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
      btn_star.setText("STAR");
      btn_star.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_starActionPerformed(evt);
         }
      });
      getContentPane().add(btn_star, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 30));

      lb_1.setFont(new java.awt.Font("Microsoft YaHei", 1, 160)); // NOI18N
      lb_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lb_1.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mousePressed(java.awt.event.MouseEvent evt) {
            lb_1MousePressed(evt);
         }
      });
      getContentPane().add(lb_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 140, 140));

      lb_2.setFont(new java.awt.Font("Microsoft YaHei", 1, 160)); // NOI18N
      lb_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lb_2.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mousePressed(java.awt.event.MouseEvent evt) {
            lb_2MousePressed(evt);
         }
      });
      getContentPane().add(lb_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 160, 140));

      lb_3.setFont(new java.awt.Font("Microsoft YaHei", 1, 160)); // NOI18N
      lb_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lb_3.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mousePressed(java.awt.event.MouseEvent evt) {
            lb_3MousePressed(evt);
         }
      });
      getContentPane().add(lb_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 140, 150));

      lb_4.setFont(new java.awt.Font("Microsoft YaHei", 1, 160)); // NOI18N
      lb_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lb_4.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mousePressed(java.awt.event.MouseEvent evt) {
            lb_4MousePressed(evt);
         }
      });
      getContentPane().add(lb_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 150, 160));

      lb_5.setFont(new java.awt.Font("Microsoft YaHei", 1, 160)); // NOI18N
      lb_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lb_5.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mousePressed(java.awt.event.MouseEvent evt) {
            lb_5MousePressed(evt);
         }
      });
      getContentPane().add(lb_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 160, 160));

      lb_6.setFont(new java.awt.Font("Microsoft YaHei", 1, 160)); // NOI18N
      lb_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lb_6.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mousePressed(java.awt.event.MouseEvent evt) {
            lb_6MousePressed(evt);
         }
      });
      getContentPane().add(lb_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 150, 160));

      lb_7.setFont(new java.awt.Font("Microsoft YaHei", 1, 160)); // NOI18N
      lb_7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lb_7.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mousePressed(java.awt.event.MouseEvent evt) {
            lb_7MousePressed(evt);
         }
      });
      getContentPane().add(lb_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 140, 140));

      lb_8.setFont(new java.awt.Font("Microsoft YaHei", 1, 160)); // NOI18N
      lb_8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lb_8.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mousePressed(java.awt.event.MouseEvent evt) {
            lb_8MousePressed(evt);
         }
      });
      getContentPane().add(lb_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, 160, 140));

      lb_9.setFont(new java.awt.Font("Microsoft YaHei", 1, 160)); // NOI18N
      lb_9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lb_9.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mousePressed(java.awt.event.MouseEvent evt) {
            lb_9MousePressed(evt);
         }
      });
      getContentPane().add(lb_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 560, 140, 140));

      jLabel1.setText("Jugador X : ");
      getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

      jLabel11.setText("Jugador 0 : ");
      getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

      lb_X.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
      lb_X.setText("0");
      getContentPane().add(lb_X, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 50, 20));

      fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/#1.png"))); // NOI18N
      getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-210, 70, 990, 640));

      jButton1.setText("Volver a Jugar");
      jButton1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
         }
      });
      getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, 30));

      lb_0.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
      lb_0.setText("0");
      getContentPane().add(lb_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 70, 20));

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void lb_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_1MousePressed
      presionar(1);
   }//GEN-LAST:event_lb_1MousePressed

   private void lb_2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_2MousePressed
   presionar(2);
   }//GEN-LAST:event_lb_2MousePressed

   private void lb_3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_3MousePressed
      presionar(3);
   }//GEN-LAST:event_lb_3MousePressed

   private void lb_4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_4MousePressed
      presionar(4);
   }//GEN-LAST:event_lb_4MousePressed

   private void lb_5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_5MousePressed
      presionar(5);
   }//GEN-LAST:event_lb_5MousePressed

   private void lb_6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_6MousePressed
      presionar(6);
   }//GEN-LAST:event_lb_6MousePressed

   private void lb_7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_7MousePressed
      presionar(7);
   }//GEN-LAST:event_lb_7MousePressed

   private void lb_8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_8MousePressed
      presionar(8);
   }//GEN-LAST:event_lb_8MousePressed

   private void lb_9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_9MousePressed
      presionar(9);
   }//GEN-LAST:event_lb_9MousePressed

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      clean();
   }//GEN-LAST:event_jButton1ActionPerformed

   private void btn_starActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_starActionPerformed
    lbs[0].setVisible(true);
    lbs[1].setVisible(true);
    lbs[2].setVisible(true);
    lbs[3].setVisible(true);
    lbs[4].setVisible(true);
    lbs[5].setVisible(true);
    lbs[6].setVisible(true);
    lbs[7].setVisible(true);
    lbs[8].setVisible(true);
    clean();
    lb_X.setText("0");
    lb_0.setText("0");
    
   }//GEN-LAST:event_btn_starActionPerformed
   public void presionar(int casilla){
      if (lbs[casilla-1].getText().equals("")) {
         lbs[casilla-1].setText(turno);
         cambiar_turno();
         ganador();
      }
      
   }
   public void cambiar_turno(){
      if (turno.equals("X")) {
         turno = "O";
      } else {
         turno = "X";
      }
   }
   public void ganador(){
      
      
      for (int i = 0; i < vs.length; i++) {
             if(lbs[vs[i][0]-1].getText().equals("X")&&
                lbs[vs[i][1]-1].getText().equals("X")&&
                lbs[vs[i][2]-1].getText().equals("X")){
            lbs[vs[i][0]-1].setBackground(Color.green);
            lbs[vs[i][1]-1].setBackground(Color.green);
            lbs[vs[i][2]-1].setBackground(Color.green);
      JOptionPane.showMessageDialog(rootPane, "GANADOR X");
      lb_X.setText(Integer.toString(Integer.parseInt(lb_X.getText())+1));
      
      clean();
   }
             if(lbs[vs[i][0]-1].getText().equals("O")&&
                lbs[vs[i][1]-1].getText().equals("O")&&
                lbs[vs[i][2]-1].getText().equals("O")){
            lbs[vs[i][0]-1].setBackground(Color.green);
            lbs[vs[i][1]-1].setBackground(Color.green);
            lbs[vs[i][2]-1].setBackground(Color.green);
      JOptionPane.showMessageDialog(rootPane, "GANADOR O");
      lb_0.setText(Integer.toString(Integer.parseInt(lb_0.getText())+1));
      clean();
             } 
         }
     
   }
   public void clean(){
            lb_1.setText("");
      lb_2.setText("");
      lb_3.setText("");
      lb_4.setText("");
      lb_5.setText("");
      lb_6.setText("");
      lb_7.setText("");
      lb_8.setText("");
      lb_9.setText("");
      
   }
   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(app_XO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(app_XO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(app_XO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(app_XO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new app_XO().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btn_star;
   private javax.swing.JLabel fondo;
   private javax.swing.JButton jButton1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel11;
   private javax.swing.JLabel lb_0;
   private javax.swing.JLabel lb_1;
   private javax.swing.JLabel lb_2;
   private javax.swing.JLabel lb_3;
   private javax.swing.JLabel lb_4;
   private javax.swing.JLabel lb_5;
   private javax.swing.JLabel lb_6;
   private javax.swing.JLabel lb_7;
   private javax.swing.JLabel lb_8;
   private javax.swing.JLabel lb_9;
   private javax.swing.JLabel lb_X;
   // End of variables declaration//GEN-END:variables
}
